### ISSUE TITLE
Request: Override app/serializers/application.js if present on install

### ISSUE THREAD

**Issue by mattmcmanus** [firebase/emberfire#250]
I just spent about 3 hours trying to figure out why `this.store.find()` wasn't working. After a bunch of digging, I realized that `ember install emberfire` it only setup the application adaptor. I already had an application serializer setup to use the REST serializer and had forgot it was there. Since the install already overrides `app/adapters/application.js`, it might make sense to add a serializer as well just to make sure things are obvious. 

If you're curious, this is what happens when `DS.RESTSerializer` tries to serialize an instantiated `Enumerable`:

```
WARNING: Encountered "0" in payload, but no model was found for model name "0" (resolved model name using client@serializer:application:.typeForRoot("0"))
ember.debug.js:5178 WARNING: Encountered "1" in payload, but no model was found for model name "1" (resolved model name using client@serializer:application:.typeForRoot("1"))
ember.debug.js:5178 WARNING: Encountered "2" in payload, but no model was found for model name "2" (resolved model name using client@serializer:application:.typeForRoot("2"))
ember.debug.js:5178 WARNING: Encountered "3" in payload, but no model was found for model name "3" (resolved model name using client@serializer:application:.typeForRoot("3"))
ember.debug.js:5178 WARNING: Encountered "4" in payload, but no model was found for model name "4" (resolved model name using client@serializer:application:.typeForRoot("4"))
ember.debug.js:5178 WARNING: Encountered "5" in payload, but no model was found for model name "5" (resolved model name using client@serializer:application:.typeForRoot("5"))
ember.debug.js:5178 WARNING: Encountered "6" in payload, but no model was found for model name "6" (resolved model name using client@serializer:application:.typeForRoot("6"))
ember.debug.js:5178 WARNING: Encountered "7" in payload, but no model was found for model name "7" (resolved model name using client@serializer:application:.typeForRoot("7"))
ember.debug.js:5178 WARNING: Encountered "8" in payload, but no model was found for model name "8" (resolved model name using client@serializer:application:.typeForRoot("8"))
ember.debug.js:5178 WARNING: Encountered "9" in payload, but no model was found for model name "9" (resolved model name using client@serializer:application:.typeForRoot("9"))
ember.debug.js:5178 WARNING: Encountered "10" in payload, but no model was found for model name "10" (resolved model name using client@serializer:application:.typeForRoot("10"))
ember.debug.js:5178 WARNING: Encountered "_super" in payload, but no model was found for model name "super" (resolved model name using client@serializer:application:.typeForRoot("_super"))
ember.debug.js:5178 WARNING: Encountered "nextObject" in payload, but no model was found for model name "nextObject" (resolved model name using client@serializer:application:.typeForRoot("nextObject"))
ember.debug.js:5178 WARNING: Encountered "firstObject" in payload, but no model was found for model name "firstObject" (resolved model name using client@serializer:application:.typeForRoot("firstObject"))
ember.debug.js:5178 WARNING: Encountered "lastObject" in payload, but no model was found for model name "lastObject" (resolved model name using client@serializer:application:.typeForRoot("lastObject"))
ember.debug.js:5178 WARNING: Encountered "contains" in payload, but no model was found for model name "contain" (resolved model name using client@serializer:application:.typeForRoot("contains"))
ember.debug.js:5178 WARNING: Encountered "getEach" in payload, but no model was found for model name "getEach" (resolved model name using client@serializer:application:.typeForRoot("getEach"))
ember.debug.js:5178 WARNING: Encountered "setEach" in payload, but no model was found for model name "setEach" (resolved model name using client@serializer:application:.typeForRoot("setEach"))
ember.debug.js:5178 WARNING: Encountered "mapBy" in payload, but no model was found for model name "mapBy" (resolved model name using client@serializer:application:.typeForRoot("mapBy"))
ember.debug.js:5178 WARNING: Encountered "mapProperty" in payload, but no model was found for model name "mapProperty" (resolved model name using client@serializer:application:.typeForRoot("mapProperty"))
ember.debug.js:5178 WARNING: Encountered "reject" in payload, but no model was found for model name "reject" (resolved model name using client@serializer:application:.typeForRoot("reject"))
ember.debug.js:5178 WARNING: Encountered "filterBy" in payload, but no model was found for model name "filterBy" (resolved model name using client@serializer:application:.typeForRoot("filterBy"))
ember.debug.js:5178 WARNING: Encountered "filterProperty" in payload, but no model was found for model name "filterProperty" (resolved model name using client@serializer:application:.typeForRoot("filterProperty"))
ember.debug.js:5178 WARNING: Encountered "rejectBy" in payload, but no model was found for model name "rejectBy" (resolved model name using client@serializer:application:.typeForRoot("rejectBy"))
ember.debug.js:5178 WARNING: Encountered "rejectProperty" in payload, but no model was found for model name "rejectProperty" (resolved model name using client@serializer:application:.typeForRoot("rejectProperty"))
ember.debug.js:5178 WARNING: Encountered "find" in payload, but no model was found for model name "find" (resolved model name using client@serializer:application:.typeForRoot("find"))
ember.debug.js:5178 WARNING: Encountered "findBy" in payload, but no model was found for model name "findBy" (resolved model name using client@serializer:application:.typeForRoot("findBy"))
ember.debug.js:5178 WARNING: Encountered "findProperty" in payload, but no model was found for model name "findProperty" (resolved model name using client@serializer:application:.typeForRoot("findProperty"))
ember.debug.js:5178 WARNING: Encountered "everyBy" in payload, but no model was found for model name "everyBy" (resolved model name using client@serializer:application:.typeForRoot("everyBy"))
ember.debug.js:5178 WARNING: Encountered "everyProperty" in payload, but no model was found for model name "everyProperty" (resolved model name using client@serializer:application:.typeForRoot("everyProperty"))
ember.debug.js:5178 WARNING: Encountered "isEvery" in payload, but no model was found for model name "isEvery" (resolved model name using client@serializer:application:.typeForRoot("isEvery"))
ember.debug.js:5178 WARNING: Encountered "any" in payload, but no model was found for model name "any" (resolved model name using client@serializer:application:.typeForRoot("any"))
ember.debug.js:5178 WARNING: Encountered "isAny" in payload, but no model was found for model name "isAny" (resolved model name using client@serializer:application:.typeForRoot("isAny"))
ember.debug.js:5178 WARNING: Encountered "anyBy" in payload, but no model was found for model name "anyBy" (resolved model name using client@serializer:application:.typeForRoot("anyBy"))
ember.debug.js:5178 WARNING: Encountered "someProperty" in payload, but no model was found for model name "someProperty" (resolved model name using client@serializer:application:.typeForRoot("someProperty"))
ember.debug.js:5178 WARNING: Encountered "invoke" in payload, but no model was found for model name "invoke" (resolved model name using client@serializer:application:.typeForRoot("invoke"))
ember.debug.js:5178 WARNING: Encountered "toArray" in payload, but no model was found for model name "toArray" (resolved model name using client@serializer:application:.typeForRoot("toArray"))
ember.debug.js:5178 WARNING: Encountered "compact" in payload, but no model was found for model name "compact" (resolved model name using client@serializer:application:.typeForRoot("compact"))
ember.debug.js:5178 WARNING: Encountered "without" in payload, but no model was found for model name "without" (resolved model name using client@serializer:application:.typeForRoot("without"))
ember.debug.js:5178 WARNING: Encountered "uniq" in payload, but no model was found for model name "uniq" (resolved model name using client@serializer:application:.typeForRoot("uniq"))
ember.debug.js:5178 WARNING: Encountered "[]" in payload, but no model was found for model name "[]" (resolved model name using client@serializer:application:.typeForRoot("[]"))
ember.debug.js:5178 WARNING: Encountered "addEnumerableObserver" in payload, but no model was found for model name "addEnumerableObserver" (resolved model name using client@serializer:application:.typeForRoot("addEnumerableObserver"))
ember.debug.js:5178 WARNING: Encountered "removeEnumerableObserver" in payload, but no model was found for model name "removeEnumerableObserver" (resolved model name using client@serializer:application:.typeForRoot("removeEnumerableObserver"))
ember.debug.js:5178 WARNING: Encountered "hasEnumerableObservers" in payload, but no model was found for model name "hasEnumerableObserver" (resolved model name using client@serializer:application:.typeForRoot("hasEnumerableObservers"))
ember.debug.js:5178 WARNING: Encountered "enumerableContentWillChange" in payload, but no model was found for model name "enumerableContentWillChange" (resolved model name using client@serializer:application:.typeForRoot("enumerableContentWillChange"))
ember.debug.js:5178 WARNING: Encountered "enumerableContentDidChange" in payload, but no model was found for model name "enumerableContentDidChange" (resolved model name using client@serializer:application:.typeForRoot("enumerableContentDidChange"))
ember.debug.js:5178 WARNING: Encountered "sortBy" in payload, but no model was found for model name "sortBy" (resolved model name using client@serializer:application:.typeForRoot("sortBy"))
ember.debug.js:5178 WARNING: Encountered "objectAt" in payload, but no model was found for model name "objectAt" (resolved model name using client@serializer:application:.typeForRoot("objectAt"))
ember.debug.js:5178 WARNING: Encountered "objectsAt" in payload, but no model was found for model name "objectsAt" (resolved model name using client@serializer:application:.typeForRoot("objectsAt"))
ember.debug.js:5178 WARNING: Encountered "addArrayObserver" in payload, but no model was found for model name "addArrayObserver" (resolved model name using client@serializer:application:.typeForRoot("addArrayObserver"))
ember.debug.js:5178 WARNING: Encountered "removeArrayObserver" in payload, but no model was found for model name "removeArrayObserver" (resolved model name using client@serializer:application:.typeForRoot("removeArrayObserver"))
ember.debug.js:5178 WARNING: Encountered "hasArrayObservers" in payload, but no model was found for model name "hasArrayObserver" (resolved model name using client@serializer:application:.typeForRoot("hasArrayObservers"))
ember.debug.js:5178 WARNING: Encountered "arrayContentWillChange" in payload, but no model was found for model name "arrayContentWillChange" (resolved model name using client@serializer:application:.typeForRoot("arrayContentWillChange"))
ember.debug.js:5178 WARNING: Encountered "arrayContentDidChange" in payload, but no model was found for model name "arrayContentDidChange" (resolved model name using client@serializer:application:.typeForRoot("arrayContentDidChange"))
ember.debug.js:24085 Error while processing route: groups.index Cannot read property 'match' of undefined TypeError: Cannot read property 'match' of undefined
    at Ember.DefaultResolver.extend.podBasedComponentsInSubdir (http://localhost:4200/assets/vendor.js:60138:76)
    at http://localhost:4200/assets/vendor.js:60190:34
    at Array.exports.default.mixin.Mixin.create.find (http://localhost:4200/assets/vendor.js:39572:30)
    at Ember.DefaultResolver.extend.findModuleName (http://localhost:4200/assets/vendor.js:60188:44)
    at resolveOther (http://localhost:4200/assets/vendor.js:60051:37)
    at superWrapper (http://localhost:4200/assets/vendor.js:28141:20)
    at exports.default.EmberObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:15454:35)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:15217:23)
    at resolve (http://localhost:4200/assets/vendor.js:12792:29)
    at Object.Registry.resolve (http://localhost:4200/assets/vendor.js:12336:21)logError @ ember.debug.js:24085defaultActionHandlers.error @ ember.debug.js:24036triggerEvent @ ember.debug.js:24140trigger @ ember.debug.js:46495Transition.trigger @ ember.debug.js:46320(anonymous function) @ ember.debug.js:46125tryCatch @ ember.debug.js:46937invokeCallback @ ember.debug.js:46949publish @ ember.debug.js:46920publishRejection @ ember.debug.js:46862(anonymous function) @ ember.debug.js:27239Queue.invoke @ ember.debug.js:871Queue.flush @ ember.debug.js:936DeferredActionQueues.flush @ ember.debug.js:741Backburner.end @ ember.debug.js:166(anonymous function) @ ember.debug.js:569
ember.debug.js:5178 WARNING: Encountered "name" in payload, but no model was found for model name "name" (resolved model name using client@serializer:application:.typeForRoot("name"))
ember.debug.js:5178 WARNING: Encountered "id" in payload, but no model was found for model name "id" (resolved model name using client@serializer:application:.typeForRoot("id"))
ember.debug.js:5162 Uncaught Error: Assertion Failed: Expected an object as `data` in a call to `push` for client@model:group: , but was undefined
```

Anyway, for me, changing `app/serializers/application.js` from

```
export default DS.RESTSerializer.extend();
```

to

```
export default DS.FirebaseSerializer.extend();
```

worked find. If you're open to this, I don't mind taking a stab at a PR for the blueprint. Should be straight forward.

**Comment by tstirrat** [comment]
it's preferable to remove the file altogether, the firebase adapter specifies a default serializer with `defaultSerializer: '-firebase'` [here](https://github.com/firebase/emberfire/blob/v1.4.4/addon/adapters/firebase.js#L37)

I'm not sure if we can get an `ember-cli` generator to remove a file, though.

**Comment by tstirrat** [comment]
I think I'd prefer it to warn when a serializer is found rather than us including an app serializer in the blueprint.

Do you think that would have been enough?

```
app/serializers/application.js found, this can conflict with emberfire and should be removed
```

maybe something like that?

**Comment by mattmcmanus** [comment]
Any visibility would be helpful. Being new to ember in general, it took me a while to even know where to look. 



Matt McManus
Independent Developer, Designer & Technical Advocate
(215) 565-5379
http://mcmanus.io

**Comment by FredUK** [comment]
Thanks a lot mattmcmanus! I was getting frustrated with my hasMany models not loading at all and throwing "emberfire Expected an object as `data` in a call to `push...`"  Removing the RESTSerializer I had for the model fixed the issue and all is well. I agree that it should throw at least a warning as it took me a couple of hours to find this solution. Thanks again  mattmcmanus!

**Comment by tstirrat** [comment]
It seems this problem keeps popping up so we should try to warn about it.

**Comment by afomi** [comment]
I saw this issue as well when adding Emberfire to an existing Ember App where I was already using the RESTSerializer.

Creating a custom Adapter resolved the `Encountered "X" in payload` issue for me.

```
// /app/adapters/adapter-name.js
import FirebaseSerializer from 'emberfire/serializers/firebase';
export default FirebaseSerializer.extend();
```
