### ISSUE TITLE
emberfire is using deprecated features

### ISSUE THREAD

**Issue by stefanpenner** [firebase/emberfire#253]
such as:

```
DEPRECATION: Usage of `typeKey` has been deprecated and will be removed in Ember Data 1.0. It has been replaced by `modelName` on the model class.
        at Function.ember$data$lib$system$store$$Service.extend.modelFor.Ember.defineProperty.get [as typeKey] (http://localhost:4200/assets/vendor.js:75396:21)
        at exports.default.DS.default.Adapter.extend._updateRecordCacheForType (http://localhost:4200/assets/vendor.js:92002:25)
        at http://localhost:4200/assets/vendor.js:91616:21
        at http://localhost:4200/assets/vendor.js:89565:12
        at fb.LLRBNode.goog.defineClass.inorderTraversal (http://localhost:4200/assets/vendor.js:81822:48)
        at fb.LLRBNode.goog.defineClass.inorderTraversal (http://localhost:4200/assets/vendor.js:81822:20)
        at fb.LLRBNode.goog.defineClass.inorderTraversal (http://localhost:4200/assets/vendor.js:81822:20)
        at fb.LLRBNode.goog.defineClass.inorderTraversal (http://localhost:4200/assets/vendor.js:81822:91)
        at fb.LLRBNode.goog.defineClass.inorderTraversal (http://localhost:4200/assets/vendor.js:81822:20)
```

which originates from https://github.com/firebase/emberfire/blob/fad605c268368abdb5988f1ffc0109b71fe32d49/addon/adapters/firebase.js#L576

c/d @igorT

**Comment by tstirrat** [comment]
thanks for the heads up on this, will get onto it

**Comment by stefanpenner** [comment]
@tstirrat thanks!
