### ISSUE TITLE
Passing classes to store methods has been removed. (Ember Data 1.0.0-beta.19)

### ISSUE THREAD

**Issue by ahaurw01** [firebase/emberfire#261]
Installing and serving the demo app gives me a whole boatload of these errors:

`Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of dummy@model:post:`

Looks like [Ember Data `1.0.0-beta.19`](http://emberjs.com/blog/2015/06/05/ember-data-1-0-beta-19-released.html) introduced this breaking change. Downgrading to `-beta.18` seems to work just fine.

Is `-beta.18` the officially supported version at this time?

**Comment by tstirrat** [comment]
Yeah, `beta.18` is the last working version, please use that until we update to use the new `>= beta.19` breaking conventions.

**Comment by ahaurw01** [comment]
Cool, thanks @tstirrat.

**Comment by tstirrat** [comment]
see #262.

I'll leave this issue open to catch any other reports of the same problem.

FYI it wont make it into an official version for a few days, I want to merge #260 and cut a `1.4.6` version first.

**Comment by tstirrat** [comment]
`beta.19` specifically is not supported, but `1.13.x` is now working in `master`

**Comment by oskarrough** [comment]
@tstirrat just tried ember and ember-data 1.13.2 with emberfire 1.4.7 and I'm still getting the deprecation. Not sure if this snippet will help.

```JavaScript
Error while processing route: channels.all Cannot read property 'modelName' of undefined TypeError: Cannot read property 'modelName' of undefined
    at ember$data$lib$system$store$$Service.extend.adapterFor (http://localhost:4000/assets/vendor.js:80115:35)
    at ember$data$lib$system$store$$Service.extend.serializerFor (http://localhost:4000/assets/vendor.js:80158:46)
    at listenForChanges (http://localhost:4000/assets/vendor.js:104868:30)
    at recordWasPushed (http://localhost:4000/assets/vendor.js:104842:14)
    at push (http://localhost:4000/assets/vendor.js:105393:23)
    at superWrapper [as push] (http://localhost:4000/assets/vendor.js:30970:20)
    at ember$data$lib$system$store$serializer$response$$_pushResourceObject (http://localhost:4000/assets/vendor.js:73036:20)
    at http://localhost:4000/assets/vendor.js:72998:20
    at Array.map (native)
    at ember$data$lib$system$store$serializer$response$$pushPayloadData (http://localhost:4000/assets/vendor.js:72997:73)
```
