### ISSUE TITLE
Assertion Failed: You must include an 'id' for undefined in an object passed to 'push'

### ISSUE THREAD

**Issue by dchersey** [firebase/emberfire#331]
Hello, I have a sample notebook app that works with ember-cli's HTTP mocks and also my rails backend using ActiveModelSerializer. 

When I hook it to firebase with ember-fire, I am able to register a user (I see it in the dashboard) but when I try to retrieve it by email, I get the following warning: 
```
WARNING: Encountered "0" in payload, but no model was found for model name "0" (resolved model name using ui@serializer:application:.modelNameFromPayloadKey("0"))
```

then this error: 
```
Error: Assertion Failed: You must include an 'id' for undefined in an object passed to 'push'
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:24735:21)
    at assert (http://localhost:4200/assets/vendor.js:14636:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:22037:34)
    at ember$data$lib$system$store$$Service.extend._pushInternalModel (http://localhost:4200/assets/vendor.js:75316:15)
    at ember$data$lib$system$store$$Service.extend.push [as _super] (http://localhost:4200/assets/vendor.js:75302:34)
    at push (http://localhost:4200/assets/vendor.js:94940:38)
    at superWrapper [as push] (http://localhost:4200/assets/vendor.js:30984:22)
    at http://localhost:4200/assets/vendor.js:70210:27
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:9707:25)
```

I am querying the store using:
```javascript

export default Ember.Route.extend({
  actions: {
    login: function() { 
      this.store.query('user', {
        email: this.controller.get('email') 
      }).then((users) => {
        if(users.get('length') === 1) {
          var user = users.objectAt(0); 
          this.controllerFor('application').set('user',user); 
          this.transitionTo('notebooks', user.get('id'));
        }
        else {
          console.log('unexpected query result'); 
        }
     }); 
    }
  } 
});
```
Digging in, I can see by setting breakpoint at finders.js#157 I am about to 
```javascript
    store._adapterRun(function () {
      var payload = normalizeResponseHelper(serializer, store, typeClass, adapterPayload, null, 'query');
      //TODO Optimize
      records = store.push(payload);
    });
```
push the payload. The adapter  payload inspects to 
```
adapterPayload: Array[1]
   0: Object 
       email: "test@test.com"
       first_name: "Test"
       id: "-K1oINClDw2ylQLww7-p"
       last_name: "User"
```
which is my user. So all's good except for the trace. Not sure about that ID but I am new to firebase; maybe it's ok. It matches what I see in my dashboard.

I haven't done anything special with my serializer -- it's vanilla.

```javascript
import DS from 'ember-data';

export default DS.RESTSerializer.extend({
});
```

AFAIK I am using the latest & greatest -- here's bower.json
```json
{
  "name": "ui",
  "dependencies": {
    "ember": "2.1.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.4",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "2.1.0",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.7",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^2.1.4",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.18.0",
    "foundation": "~5.5.3",
    "bootstrap": "~3.3.5",
    "showdown": "~1.3.0",
    "firebase": "^2.1.0"
  }
}
```

and my dev dependencies in package.json
```javascript
  "devDependencies": {
    "body-parser": "^1.14.1",
    "broccoli-asset-rev": "^2.1.2",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "1.0.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-htmlbars": "1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-rails-addon": "0.0.12",
    "ember-cli-release": "0.2.3",
    "ember-cli-showdown": "2.5.0",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "2.1.0",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "emberfire": "1.6.0",
    "express": "^4.13.3",
    "glob": "^4.5.3",
    "morgan": "^1.6.1",
    "nedb": "^1.2.1"
  }
```
Any pointers/help/guidance would be great!  I am also new to ember too, so maybe I am missing  the obvious?

**Comment by brenoinojosa** [comment]
I don't think that's related to firebase.... I've got the same problem but I'm proxying through a java webserver. So no firebase here... I'm using DS.RESTAdapter. I guess it's something to do with the model or the response itself.

**Comment by dchersey** [comment]
Thank you!  I was able to get past it; I found out that I needed to call normalize on the JSON I received.
My model is a notebook object, so: 
```
          var normalizedData = self.store.normalize('notebook',$.parseJSON(e.data))
          self.store.push(normalizedData);
```

**Comment by tstirrat** [comment]
Are you using the **DS.RESTAdapter** to connect to Firebase via REST calls? or are you using **FirebaseAdapter** (which uses the realtime websocket connection)?

If you are using **FirebaseAdapter**, you will run into problems if you are pairing this with **DS.RESTSerializer**. It should be paired with the **FirebaseSerializer**.

**Comment by nmichalares** [comment]
@dchersey Where did you put the call to normalize the data?

I'm looking at this and believe it *may* fix my issue, but not sure if it needs to be in the serializer extension, the controller or the model itself.

**Comment by dchersey** [comment]
I put the normalize call in the route, which is essentially the new controller for Ember 2.0 apps. 
If you are using a controller, it would go there. 

Hope this helps!

**Comment by tstirrat** [comment]
Thanks, this seems to be about REST adapters and not EmberFire's adapter.
