### ISSUE TITLE
Deprecation Warning: Using the injected `container` is deprecated.

### ISSUE THREAD

**Issue by duro** [firebase/emberfire#396]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.5.1
DEBUG: Ember Data : 2.6.1
DEBUG: Firebase   : 3.0.5
DEBUG: EmberFire  : 2.0.0
DEBUG: jQuery     : 2.2.4
DEBUG: -------------------------------
```

### Steps to reproduce

Use `this.get('session').fetch()` in a beforeModel route hook.

```
// /app/routes/application.js
export default Ember.Route.extend({
  beforeModel() {
    return this.get('session').fetch().catch(function(){});
  }
});
```

### Expected behavior

Should not throw a deprecation warning

### Actual behavior

Throws the following warning:

```
Using the injected `container` is deprecated. Please use the `getOwner` helper to access the owner of this object and then call `_lookupFactory` instead. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16472:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16380:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16472:7)
        at invoke (http://localhost:4200/assets/vendor.js:16488:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16441:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26480:37)
        at Object.lookupFactory (http://localhost:4200/assets/vendor.js:43550:24)
        at Object.create (http://localhost:4200/assets/vendor.js:95008:42)
        at instantiate (http://localhost:4200/assets/vendor.js:11633:23)
```

I have traced this down to line 38 in the `addon/torii-providers/firebase.js` file:

```
      default:
        const ProviderClass = this.container.lookupFactory(`firebase-auth-provider:${providerId}`);
        if (!ProviderClass) {
          return this.waitFor_(reject(new Error('Unknown provider')));
        }
```

This needs to be changed over to use the `getOwner` method of looking things up.

See: http://emberjs.com/deprecations/v2.x/#toc_injected-container-access

**Comment by mohitsud** [comment]
Bump!
It would be great if this change could be made.

**Comment by roscorcoran** [comment]
Agreed would also like to see this fixed

**Comment by brendanoh** [comment]
This seems like it will be ok until Ember 3.0 and a PR with fix was merged into Master on July 7th.

So I think if you point to master it will go away until they cut another release.

**Comment by mminkoff** [comment]
As elsewhere, [ember-cli-deprecation-workflow](https://github.com/mixonic/ember-cli-deprecation-workflow/) is your friend here.

**Comment by deckyfx** [comment]
+1 for this, 

Still no workaround?

**Comment by jamesdaniels** [comment]
We're cutting 2.0.2 today, this includes the fix.
