### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./firebase-browser.js' at server launch

### ISSUE THREAD

**Issue by mminkoff** [firebase/emberfire#489]
I'd appreciate any insight on this.  I'm on Ember 2.11.1.  Emberfire 2.0.5 loads fine but after upgrading to 2.0.6 it can't find firebase-browser.js.  I can go back and forth between the two with the same results.

I am not able to duplicate the problem in a new app even after adding in all of my addons.  I have cleaned caches, deleted dist, tmp, node_modules, and bower_components and reinstalled with no luck.  I've also updated all of my addons.

Here's the entire error:

```~/S/fran-stack $ ember s --live-reload-port 49155                                                                                        13 changed files  develop
Livereload server on http://localhost:49155
Serving on http://localhost:4200/
Entry module not found: Error: Cannot resolve 'file' or 'directory' ./firebase-browser.js in /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0
resolve file
  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js doesn't exist
  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js.webpack.js doesn't exist
  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js.web.js doesn't exist
  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js.js doesn't exist
  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js.json doesn't exist
resolve directory
  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js doesn't exist (directory default file)
  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js/package.json doesn't exist (directory description file) 0 [ 'Entry module not found: Error: Cannot resolve \'file\' or \'directory\' ./firebase-browser.js in /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0\nresolve file\n  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js doesn\'t exist\n  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js.webpack.js doesn\'t exist\n  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js.web.js doesn\'t exist\n  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js.js doesn\'t exist\n  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js.json doesn\'t exist\nresolve directory\n  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js doesn\'t exist (directory default file)\n  /Users/max/Sites/fran-stack/tmp/webpack_writer-input_base_path-DN7k0h3y.tmp/0/firebase-browser.js/package.json doesn\'t exist (directory description file)' ]
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
TypeError: Cannot read property 'stack' of null
    at /Users/max/Sites/fran-stack/node_modules/broccoli-builder/lib/builder.js:164:24
    at tryCatch (/Users/max/Sites/fran-stack/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/max/Sites/fran-stack/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/max/Sites/fran-stack/node_modules/rsvp/dist/rsvp.js:521:7)
    at publishRejection (/Users/max/Sites/fran-stack/node_modules/rsvp/dist/rsvp.js:456:3)
    at flush (/Users/max/Sites/fran-stack/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/max/Sites/fran-stack/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/max/Sites/fran-stack/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/max/Sites/fran-stack/node_modules/broccoli-merge-trees/index.js:36:53)
    at Class.treeForVendor (/Users/max/Sites/fran-stack/node_modules/emberfire/index.js:52:12)
    at Class._treeFor (/Users/max/Sites/fran-stack/node_modules/ember-cli/lib/models/addon.js:362:33)
    at Class.treeFor (/Users/max/Sites/fran-stack/node_modules/ember-cli/lib/models/addon.js:330:21)
    at /Users/max/Sites/fran-stack/node_modules/ember-cli/lib/broccoli/ember-app.js:522:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/max/Sites/fran-stack/node_modules/ember-cli/lib/broccoli/ember-app.js:520:30)
    at EmberApp._processedVendorTree (/Users/max/Sites/fran-stack/node_modules/ember-cli/lib/broccoli/ember-app.js:975:29)
```

I wish I could reproduce this elsewhere.  Thanks for any suggestions anyone might have.

**Comment by srindom** [comment]
I have the same issue. Did you find a fix?

**Comment by mminkoff** [comment]
@srindom sorry, no.  I'm stuck on 2.0.5 for now.

**Comment by ibroadfo** [comment]
The cause of this issue for me is a conflicting version of `firebase` being depended on by another package, in my case `ember-cli-deploy-firebase` depending on `firebase-tools` which in turn depends on `firebase@2.x.x`.

My `npm ls firebase` looks like

```
$ npm ls firebase
flowerpot@0.0.1-prerelease /Users/ibroadfo/src/flowerpot
├─┬ ember-cli-deploy-firebase-pack@0.2.4
│ └─┬ ember-cli-deploy-firebase@0.2.7
│   └─┬ firebase-tools@3.5.0
│     └── firebase@2.4.2 
└─┬ emberfire@2.0.6
  └── firebase@3.7.3 
```

One reason this is hard to reproduce is that npm install order matters; sometimes one version will win, sometimes the other.

Possible solutions include emberfire adding some logic to detect package versions or firebase-tools upgrading their version of the firebase package.

**Comment by ibroadfo** [comment]
so I've thrown together a trivial reproduction: https://github.com/ibroadfo/dimplexity , it just has 2 dependencies which pull in conflicting versions of `firebase` as you can see here https://travis-ci.org/ibroadfo/dimplexity/builds/219268153#L1451

**Comment by voltivo** [comment]
I fixed this with a "npm install firebase"

**Comment by mminkoff** [comment]
@voltivo's solution worked for me too

**Comment by mminkoff** [comment]
I had the problem again and this time had to specify `npm install firebase@3.9.0`

**Comment by Luiz-N** [comment]
@mminkoff's solution worked for me... Does this mean we need to pre-install firebase when deploying?

**Comment by danmalone89** [comment]
Has anyone found a more viable fix to this?
